# Generated by Django 4.0.5 on 2022-06-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpensesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='money',
            field=models.FloatField(),
        ),
    ]
