# Generated by Django 4.0.5 on 2022-06-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpensesApp', '0002_alter_expense_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
