# Generated by Django 4.0.5 on 2022-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpensesApp', '0007_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(default='gwJuOMwm4ELvVG3CVVNu96d3kspRWNTh'),
        ),
    ]
